### ISSUE TITLE
Hover effect is annoying as hell

### ISSUE THREAD

**Issue by pgalkin** [SaijoGeorge/HelpMeBuild#1]
Sorry to say. I just can't stomach it because it's way too jumpy. If you move your cursor fast enough the thumbnails change in size, and it feels ridiculous. How about a drop down text on top of the thumbnail? Something like http://tympanus.net/Development/HoverEffectIdeas/ at Zoe. Otherwise great site, I have found a few useful things!

**Comment by SaijoGeorge** [comment]
thanks mate. I am looking at a better way to do the hover effect, thanks for link to codrops :)
